### ISSUE TITLE
 Plugin Password is  is clear text in html

### ISSUE THREAD

**Issue by zer0coldai** [dolphindb/grafana-datasource#18]
![微信图片_20231213162253](https://github.com/dolphindb/grafana-datasource/assets/153716793/28656117-4239-457c-afea-723e2df7d285)

**Comment by ShenHongFei** [comment]
应该是可以隐藏的，antd 组件支持隐藏
https://github.com/ant-design/ant-design/issues/7761

目前 grafana 插件用的是 grafana 提供的组件 (https://www.npmjs.com/package/@grafana/ui) ，可能把这个 issue 提给 grafana 那边让他们来修复比较好？
https://github.com/grafana/grafana

**Comment by ShenHongFei** [comment]
![image](https://github.com/dolphindb/grafana-datasource/assets/15074472/6ba41f1a-c251-486f-bd41-2d73d7b1254a)

![image](https://github.com/dolphindb/grafana-datasource/assets/15074472/f7ea17dc-33a2-4d9b-a46a-2c28b70323aa)

@cryptozer0cold

**Comment by ShenHongFei** [comment]
https://github.com/grafana/grafana/blob/43356e28e7d2bddac0fbfff8a6a89720985a357e/packages/grafana-ui/src/components/SecretInput/SecretInput.tsx

grafana 有一个 SecretInput 组件，但是依然显示了密码，似乎也没有用

https://developers.grafana.com/ui/latest/index.html?path=/story/forms-secretinput--basic&args=placeholder:placeholder

![image](https://github.com/dolphindb/grafana-datasource/assets/15074472/7512b438-5386-4e0d-8b2f-d8d2c95e584c)

**Comment by ShenHongFei** [comment]
https://github.com/ant-design/ant-design/issues/19959
